spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 5f90237f-3796-47e9-9afd-258fba2843ab
        group: shhsca
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: shhsca-GlobalTransactional

# management
management:
  endpoints:
    web:
      exposure:
        include: "*"

