server:
  port: 8071

spring:
  application:
    name: shhsca-registry-consul-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
