server:
  port: 8050
  servlet:
    context-path: /ws

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: wms-service
  profiles:
    active: dev
  output:
    ansi:
      enabled: always #使用色彩输出提高日志可读性

