server:
  port: 8030
  servlet:
    context-path: /ss

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: stock-service
  profiles:
    active: dev
  output:
    ansi:
      enabled: always #使用色彩输出提高日志可读性

