server:
  port: 8040
  servlet:
    context-path: /cs

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: credit-service
  profiles:
    active: dev
  output:
    ansi:
      enabled: always #使用色彩输出提高日志可读性

